# Generated by Django 4.2.5 on 2023-11-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='auth_tag',
            field=models.BinaryField(default=b''),
        ),
    ]
